name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.7.0
  font_awesome_flutter: ^10.4.0
  dio: ^4.0.6
  double_back_to_close_app: ^2.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Lato
    fonts:
      - assets: assets\fonts\Lato-Regular.ttf
